apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: country-service-policy
  namespace: country-service
spec:
  podSelector:
    matchLabels:
      app: country-service
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: nginx-ingress
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
