apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airport-service-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx 
  rules:
  - host: airport-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.service.port }}  
