name: country-service
replicaCount: 1

image:
  repository: dhenob/viwell-country-service
  pullPolicy: IfNotPresent
  tag: 0.0.1

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000

containerSecurityContext:
  capabilities:
    drop:
      - ALL
    add: ["NET_ADMIN"]
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8000
  targetPort: 8080

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

startupProbe:
  initialDelaySeconds: 60
  periodSeconds: 5
  failureThreshold: 30

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5


namespace: "country-service"

ingress:
  enabled: true
  hosts:
    - host: country-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: country-service
              port:
                number: 8000
  tls: []
