# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: country-service
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/dhenob/VIwell-Assessment.git'
#     path: apps/country-service/helm-chart
#     targetRevision: HEAD
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: country-service
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
