name: Update and Release Helm Chart

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to use in Helm chart (e.g., 1.0.1, 1.1.0)'
        required: true
      service:
        description: 'Service whose Helm chart is to be updated (e.g., airport, country)'
        required: true

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Helm chart image tag
      run: |
        CHART_PATH="./apps/${{ github.event.inputs.service }}-service/helm-chart/values.yaml"
        sed -i "s/tag: .*/tag: ${{ github.event.inputs.tag }}/" $CHART_PATH
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check for changes
        git add $CHART_PATH
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update image tag to ${{ github.event.inputs.tag }} in Helm chart for ${{ github.event.inputs.service }}"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
        fi
